-- Independent follow-up review 2026-08-24 P1-1: "Retry still resends the
-- previous user question as a new message... Add an idempotent answer-attempt
-- endpoint tied to the original user_message_id... Preserve attempt history
-- without duplicating conversation history or billable work." A retry now
-- regenerates and updates the SAME failed assistant message row in place
-- (routes_chat.py's retry_answer) instead of app.js resubmitting the
-- question as a brand-new user turn -- no duplicate user message, no second
-- unrelated assistant message.
--
-- answer_status vocabulary (see migration 0002) gains a transient
-- 'retrying' state: retry_answer atomically claims a message with
-- `UPDATE messages SET answer_status='retrying' WHERE id=? AND
-- answer_status='failed'` before calling the provider again -- the same
-- claim-UPDATE idempotency pattern conversations.pending_message_id already
-- uses (migration 0005/P1-8) -- so a double-tap on the retry button can
-- only ever trigger one provider call, not two concurrent ones.
--
-- retry_count is the "preserve attempt history" half: how many times this
-- answer has been retried, visible to an admin/technician without needing a
-- full per-attempt content log (a materially larger feature, not built here
-- -- see docs/PRODUCTION_READINESS.md).
ALTER TABLE messages ADD COLUMN retry_count INTEGER NOT NULL DEFAULT 0;
